var searchData=
[
  ['c_2b_2b_0',['C++',['../group__cpp.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_1',['Callback functions from Kodi to add-on',['../group__cpp__kodi__gui__windows__window__callbacks.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_2',['Callback functions from Kodi to Add-On',['../group__python___player_c_b.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_3',['Callback functions from Kodi to add-on',['../group__python__xbmcgui__window__cb.html',1,'']]],
  ['callbacks_20getdirectory_28_29_4',['Callbacks GetDirectory()',['../group__cpp__kodi__addon__vfs__general__cb___get_directory.html',1,'']]],
  ['child_20functions_5',['Child Functions',['../group__cpp__kodi__gui__helpers__gl___c_shader_program__child.html',1,'']]],
  ['class_20audiodecoderinfotag_6',['class AudioDecoderInfoTag',['../group__cpp__kodi__addon__audiodecoder___defs___audio_decoder_info_tag.html',1,'']]],
  ['class_20audioengineformat_7',['class AudioEngineFormat',['../group__cpp__kodi__audioengine___defs___audio_engine_format.html',1,'']]],
  ['class_20cachestatus_8',['class CacheStatus',['../group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['class_20caddonbase_9',['class CAddonBase',['../group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['class_20caestream_10',['class CAEStream',['../group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['class_20cdirentry_11',['class CDirEntry',['../group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['class_20cdllhelper_12',['class CDllHelper',['../group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['class_20cendtime_13',['class CEndTime',['../group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['class_20cinterfaceandroidsystem_14',['class CInterfaceAndroidSystem',['../group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20csettingvalue_15',['class CSettingValue',['../group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['class_20cthread_16',['class CThread',['../group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['class_20ctimer_17',['class CTimer',['../group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['class_20driverprimitive_18',['class DriverPrimitive',['../group__cpp__kodi__addon__peripheral___defs___joystick___driver_primitive.html',1,'']]],
  ['class_20filestatus_19',['class FileStatus',['../group__cpp__kodi__vfs___defs___file_status.html',1,'']]],
  ['class_20gamecontrollerlayout_20',['class GameControllerLayout',['../group__cpp__kodi__addon__game___defs___input_types___game_controller_layout.html',1,'']]],
  ['class_20httpheader_21',['class HttpHeader',['../group__cpp__kodi__vfs___defs___http_header.html',1,'']]],
  ['class_20inputstreamcapabilities_22',['class InputstreamCapabilities',['../group__cpp__kodi__addon__inputstream___defs___interface___inputstream_capabilities.html',1,'']]],
  ['class_20inputstreamcontentlightmetadata_23',['class InputstreamContentlightMetadata',['../group__cpp__kodi__addon__inputstream___defs___interface___inputstream_contentlight_metadata.html',1,'']]],
  ['class_20inputstreaminfo_24',['class InputstreamInfo',['../group__cpp__kodi__addon__inputstream___defs___interface___inputstream_info.html',1,'']]],
  ['class_20inputstreammasteringmetadata_25',['class InputstreamMasteringMetadata',['../group__cpp__kodi__addon__inputstream___defs___interface___inputstream_mastering_metadata.html',1,'']]],
  ['class_20inputstreamproperty_26',['class InputstreamProperty',['../group__cpp__kodi__addon__inputstream___defs___inputstream_property.html',1,'']]],
  ['class_20inputstreamtimes_27',['class InputstreamTimes',['../group__cpp__kodi__addon__inputstream___defs___interface___inputstream_times.html',1,'']]],
  ['class_20itimercallback_28',['class ITimerCallback',['../group__cpp__kodi__tools___c_timer___c_b.html',1,'']]],
  ['class_20joystick_29',['class Joystick',['../group__cpp__kodi__addon__peripheral___defs___joystick___joystick.html',1,'']]],
  ['class_20joystickfeature_30',['class JoystickFeature',['../group__cpp__kodi__addon__peripheral___defs___joystick___joystick_feature.html',1,'']]],
  ['class_20peripheral_31',['class Peripheral',['../group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral.html',1,'']]],
  ['class_20peripheralcapabilities_32',['class PeripheralCapabilities',['../group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities.html',1,'']]],
  ['class_20peripheralevent_33',['class PeripheralEvent',['../group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event.html',1,'']]],
  ['class_20pvrcapabilities_34',['class PVRCapabilities',['../group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities.html',1,'']]],
  ['class_20pvrchannel_35',['class PVRChannel',['../group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channel.html',1,'']]],
  ['class_20pvrchannelgroup_36',['class PVRChannelGroup',['../group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group.html',1,'']]],
  ['class_20pvrchannelgroupmember_37',['class PVRChannelGroupMember',['../group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_member.html',1,'']]],
  ['class_20pvrchannelgroupmembersresultset_38',['class PVRChannelGroupMembersResultSet',['../group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_members_result_set.html',1,'']]],
  ['class_20pvrchannelgroupsresultset_39',['class PVRChannelGroupsResultSet',['../group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_groups_result_set.html',1,'']]],
  ['class_20pvrchannelsresultset_40',['class PVRChannelsResultSet',['../group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channels_result_set.html',1,'']]],
  ['class_20pvrcodec_41',['class PVRCodec',['../group__cpp__kodi__addon__pvr___defs___stream___p_v_r_codec.html',1,'']]],
  ['class_20pvrdescrambleinfo_42',['class PVRDescrambleInfo',['../group__cpp__kodi__addon__pvr___defs___channel___p_v_r_descramble_info.html',1,'']]],
  ['class_20pvredlentry_43',['class PVREDLEntry',['../group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r_e_d_l_entry.html',1,'']]],
  ['class_20pvrepgtag_44',['class PVREPGTag',['../group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tag.html',1,'']]],
  ['class_20pvrepgtagsresultset_45',['class PVREPGTagsResultSet',['../group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tags_result_set.html',1,'']]],
  ['class_20pvrmenuhook_46',['class PVRMenuhook',['../group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r_menuhook.html',1,'']]],
  ['class_20pvrprovider_47',['class PVRProvider',['../group__cpp__kodi__addon__pvr___defs___p_v_r_provider.html',1,'']]],
  ['class_20pvrprovidersresultset_48',['class PVRProvidersResultSet',['../group__cpp__kodi__addon__pvr___defs___p_v_r_providers_result_set.html',1,'']]],
  ['class_20pvrrecording_49',['class PVRRecording',['../group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recording.html',1,'']]],
  ['class_20pvrrecordingsresultset_50',['class PVRRecordingsResultSet',['../group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recordings_result_set.html',1,'']]],
  ['class_20pvrsignalstatus_51',['class PVRSignalStatus',['../group__cpp__kodi__addon__pvr___defs___channel___p_v_r_signal_status.html',1,'']]],
  ['class_20pvrstreamproperties_52',['class PVRStreamProperties',['../group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties.html',1,'']]],
  ['class_20pvrstreamproperty_53',['class PVRStreamProperty',['../group__cpp__kodi__addon__pvr___defs___general___inputstream___p_v_r_stream_property.html',1,'']]],
  ['class_20pvrstreamproperty_20_26_20definition_20pvr_5fstream_5fproperty_54',['class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY',['../group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'']]],
  ['class_20pvrstreamtimes_55',['class PVRStreamTimes',['../group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times.html',1,'']]],
  ['class_20pvrtimer_56',['class PVRTimer',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer.html',1,'']]],
  ['class_20pvrtimersresultset_57',['class PVRTimersResultSet',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timers_result_set.html',1,'']]],
  ['class_20pvrtimertype_58',['class PVRTimerType',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type.html',1,'']]],
  ['class_20pvrtypeintvalue_59',['class PVRTypeIntValue',['../group__cpp__kodi__addon__pvr___defs___p_v_r_type_int_value.html',1,'']]],
  ['class_20streamcryptosession_60',['class StreamCryptoSession',['../group__cpp__kodi__addon__inputstream___defs___stream_encryption___stream_crypto_session.html',1,'']]],
  ['class_20stringutils_61',['class StringUtils',['../group__cpp__kodi__tools___string_utils.html',1,'']]],
  ['class_20vfsurl_62',['class VFSUrl',['../group__cpp__kodi__addon__vfs___defs___v_f_s_url.html',1,'']]],
  ['class_20videocodecinitdata_63',['class VideoCodecInitdata',['../group__cpp__kodi__addon__videocodec___defs___video_codec_initdata.html',1,'']]],
  ['class_20visualizationtrack_64',['class VisualizationTrack',['../group__cpp__kodi__addon__visualization___defs___visualization_track.html',1,'']]],
  ['class_3a_20cstream_65',['Class: CStream',['../group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['cmake_20addon_20creation_20structure_66',['CMake addon creation structure',['../group__cpp__cmake.html',1,'']]],
  ['control_67',['Control',['../group__python__xbmcgui__control.html',1,'']]],
  ['control_20button_68',['Control Button',['../group__cpp__kodi__gui__windows__controls___c_button.html',1,'']]],
  ['control_20edit_69',['Control Edit',['../group__cpp__kodi__gui__windows__controls___c_edit.html',1,'']]],
  ['control_20fade_20label_70',['Control Fade Label',['../group__cpp__kodi__gui__windows__controls___c_fade_label.html',1,'']]],
  ['control_20image_71',['Control Image',['../group__cpp__kodi__gui__windows__controls___c_image.html',1,'']]],
  ['control_20label_72',['Control Label',['../group__cpp__kodi__gui__windows__controls___c_label.html',1,'']]],
  ['control_20progress_73',['Control Progress',['../group__cpp__kodi__gui__windows__controls___c_progress.html',1,'']]],
  ['control_20radio_20button_74',['Control Radio Button',['../group__cpp__kodi__gui__windows__controls___c_radio_button.html',1,'']]],
  ['control_20rendering_75',['Control Rendering',['../group__cpp__kodi__gui__windows__controls___c_rendering.html',1,'']]],
  ['control_20settings_20slider_76',['Control Settings Slider',['../group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'']]],
  ['control_20slider_77',['Control Slider',['../group__cpp__kodi__gui__windows__controls___c_slider.html',1,'']]],
  ['control_20spin_78',['Control Spin',['../group__cpp__kodi__gui__windows__controls___c_spin.html',1,'']]],
  ['control_20text_20box_79',['Control Text Box',['../group__cpp__kodi__gui__windows__controls___c_text_box.html',1,'']]],
  ['controller_20input_80',['Controller Input',['../group__cpp__kodi__addon__peripheral___docs___controller_input.html',1,'']]]
];
