var group__cpp__kodi__gui =
[
    [ "Control Button", "de/d24/group__cpp__kodi__gui__controls___c_button.html", null ],
    [ "Control Edit", "db/d15/group__cpp__kodi__gui__controls___c_edit.html", "db/d15/group__cpp__kodi__gui__controls___c_edit" ],
    [ "Control Fade Label", "db/dbd/group__cpp__kodi__gui__controls___c_fade_label.html", "db/dbd/group__cpp__kodi__gui__controls___c_fade_label" ],
    [ "Control Image", "d4/d3f/group__cpp__kodi__gui__controls___c_image.html", "d4/d3f/group__cpp__kodi__gui__controls___c_image" ],
    [ "Control Label", "de/d64/group__cpp__kodi__gui__controls___c_label.html", "de/d64/group__cpp__kodi__gui__controls___c_label" ],
    [ "Control Progress", "d6/d8c/group__cpp__kodi__gui__controls___c_progress.html", "d6/d8c/group__cpp__kodi__gui__controls___c_progress" ],
    [ "Control Radio Button", "d9/dfe/group__cpp__kodi__gui__controls___c_radio_button.html", "d9/dfe/group__cpp__kodi__gui__controls___c_radio_button" ],
    [ "Control Rendering", "d0/da2/group__cpp__kodi__gui__controls___c_rendering.html", "d0/da2/group__cpp__kodi__gui__controls___c_rendering" ],
    [ "Control Settings Slider", "dd/d10/group__cpp__kodi__gui__controls___c_settings_slider.html", "dd/d10/group__cpp__kodi__gui__controls___c_settings_slider" ],
    [ "Control Slider", "de/d1b/group__cpp__kodi__gui__controls___c_slider.html", "de/d1b/group__cpp__kodi__gui__controls___c_slider" ],
    [ "Control Spin", "dc/d36/group__cpp__kodi__gui__controls___c_spin.html", "dc/d36/group__cpp__kodi__gui__controls___c_spin" ],
    [ "Control Text Box", "d4/dc0/group__cpp__kodi__gui__controls___c_text_box.html", "d4/dc0/group__cpp__kodi__gui__controls___c_text_box" ],
    [ "Dialog Context Menu", "de/d4c/group__cpp__kodi__gui__dialogs___context_menu.html", "de/d4c/group__cpp__kodi__gui__dialogs___context_menu" ],
    [ "Dialog Extended Progress", "d8/d50/group__cpp__kodi__gui__dialogs___c_extended_progress.html", "d8/d50/group__cpp__kodi__gui__dialogs___c_extended_progress" ],
    [ "Dialog File Browser", "dc/dcb/group__cpp__kodi__gui__dialogs___file_browser.html", "dc/dcb/group__cpp__kodi__gui__dialogs___file_browser" ],
    [ "Dialog Keyboard", "d6/db3/group__cpp__kodi__gui__dialogs___keyboard.html", "d6/db3/group__cpp__kodi__gui__dialogs___keyboard" ],
    [ "Dialog Numeric", "d0/d8d/group__cpp__kodi__gui__dialogs___numeric.html", "d0/d8d/group__cpp__kodi__gui__dialogs___numeric" ],
    [ "Dialog OK", "d5/db4/group__cpp__kodi__gui__dialogs___o_k.html", "d5/db4/group__cpp__kodi__gui__dialogs___o_k" ],
    [ "Dialog Progress", "db/dd0/group__cpp__kodi__gui__dialogs___c_progress.html", "db/dd0/group__cpp__kodi__gui__dialogs___c_progress" ],
    [ "Dialog Select", "d6/da0/group__cpp__kodi__gui__dialogs___select.html", "d6/da0/group__cpp__kodi__gui__dialogs___select" ],
    [ "Dialog Text Viewer", "d5/d5f/group__cpp__kodi__gui__dialogs___text_viewer.html", "d5/d5f/group__cpp__kodi__gui__dialogs___text_viewer" ],
    [ "Dialog Yes/No", "d4/dc5/group__cpp__kodi__gui__dialogs___yes_no.html", "d4/dc5/group__cpp__kodi__gui__dialogs___yes_no" ],
    [ "List Item", "d9/d7a/group__cpp__kodi__gui___c_list_item.html", "d9/d7a/group__cpp__kodi__gui___c_list_item" ],
    [ "Window", "d6/ddc/group__cpp__kodi__gui___c_window.html", "d6/ddc/group__cpp__kodi__gui___c_window" ],
    [ "kodi::gui::GetCurrentWindowDialogId", "dc/d5f/group__cpp__kodi__gui.html#gadf76157bc1390d4ecde633fceb1f6a60", null ],
    [ "kodi::gui::GetCurrentWindowId", "dc/d5f/group__cpp__kodi__gui.html#ga77c37316fbb989c04e58cc10c0631627", null ],
    [ "kodi::gui::GetScreenHeight", "dc/d5f/group__cpp__kodi__gui.html#gab077c46206c510dbbc3f8e37a536407f", null ],
    [ "kodi::gui::GetScreenWidth", "dc/d5f/group__cpp__kodi__gui.html#ga4d8891c85b766bddbd2386184e892acd", null ],
    [ "kodi::gui::GetVideoResolution", "dc/d5f/group__cpp__kodi__gui.html#gadf2199dfe26657ae194c79e18e41edd8", null ],
    [ "kodi::gui::Lock", "dc/d5f/group__cpp__kodi__gui.html#gafc92f24c22d2dff1158bad6cbc771d87", null ],
    [ "kodi::gui::Unlock", "dc/d5f/group__cpp__kodi__gui.html#ga6c6c14ee83364161f2dab4233f1fd95f", null ]
];