var searchData=
[
  ['ref_0',['Ref',['../d5/d38/class_x_b_m_c_addon_1_1_addon_class_1_1_ref.html',1,'XBMCAddon::AddonClass']]],
  ['ref_1',['ref',['../db/dd5/class_x_b_m_c_addon_1_1xbmcgui_1_1ref.html',1,'XBMCAddon::xbmcgui']]],
  ['refreshoverride_2',['RefreshOverride',['../d2/db1/struct_refresh_override.html',1,'']]],
  ['refreshrate_3',['REFRESHRATE',['../d9/d4c/struct_r_e_f_r_e_s_h_r_a_t_e.html',1,'']]],
  ['refreshvideolatency_4',['RefreshVideoLatency',['../d5/d5c/struct_refresh_video_latency.html',1,'']]],
  ['registers_5ft_5',['registers_t',['../dd/d62/structregisters__t.html',1,'']]],
  ['reinstalled_6',['ReInstalled',['../dc/d2a/struct_a_d_d_o_n_1_1_addon_events_1_1_re_installed.html',1,'ADDON::AddonEvents']]],
  ['releasetypeinfo_7',['ReleaseTypeInfo',['../dc/df5/struct_release_type_info.html',1,'']]],
  ['remove_5frvalue_5freference_8',['remove_rvalue_reference',['../d8/d94/structremove__rvalue__reference.html',1,'']]],
  ['remove_5frvalue_5freference_3c_20t_20_26_20_3e_9',['remove_rvalue_reference&lt; T &amp; &gt;',['../d2/d8c/structremove__rvalue__reference_3_01_t_01_6_01_4.html',1,'']]],
  ['remove_5frvalue_5freference_3c_20t_20_26_26_20_3e_10',['remove_rvalue_reference&lt; T &amp;&amp; &gt;',['../de/dc1/structremove__rvalue__reference_3_01_t_01_6_6_01_4.html',1,'']]],
  ['remove_5frvalue_5freference_3c_20t_20_2a_20_3e_11',['remove_rvalue_reference&lt; T * &gt;',['../df/d47/structremove__rvalue__reference_3_01_t_01_5_01_4.html',1,'']]],
  ['renderbufferpools_12',['RenderBufferPools',['../d5/d2a/struct_k_o_d_i_1_1_r_e_t_r_o_1_1_c_render_buffer_manager_1_1_render_buffer_pools.html',1,'KODI::RETRO::CRenderBufferManager']]],
  ['rendercapture_13',['RenderCapture',['../d0/dab/class_x_b_m_c_addon_1_1xbmc_1_1_render_capture.html',1,'XBMCAddon::xbmc']]],
  ['rendererdetail_14',['RendererDetail',['../d6/db1/struct_renderer_detail.html',1,'']]],
  ['rendermethoddetail_15',['RenderMethodDetail',['../de/d82/struct_render_method_detail.html',1,'']]],
  ['replaygain_16',['ReplayGain',['../d7/d7e/class_replay_gain.html',1,'']]],
  ['replaygainsettings_17',['ReplayGainSettings',['../dc/ddc/struct_replay_gain_settings.html',1,'']]],
  ['repositoryupdated_18',['RepositoryUpdated',['../d2/db1/struct_a_d_d_o_n_1_1_c_repository_updater_1_1_repository_updated.html',1,'ADDON::CRepositoryUpdater']]],
  ['resolution_5finfo_19',['RESOLUTION_INFO',['../db/d94/struct_r_e_s_o_l_u_t_i_o_n___i_n_f_o.html',1,'']]],
  ['resolution_5fwhr_20',['RESOLUTION_WHR',['../d9/d18/struct_r_e_s_o_l_u_t_i_o_n___w_h_r.html',1,'']]],
  ['resolutionupdateinfo_21',['ResolutionUpdateInfo',['../de/d43/struct_resolution_update_info.html',1,'']]],
  ['resolveresult_22',['ResolveResult',['../d2/da7/struct_a_d_d_o_n_1_1_c_repository_1_1_resolve_result.html',1,'ADDON::CRepository']]],
  ['resourceprioritysort_23',['ResourcePrioritySort',['../d2/dda/struct_u_p_n_p_1_1_resource_priority_sort.html',1,'UPNP']]],
  ['result_5fset_24',['result_set',['../dc/d6e/classdbiplus_1_1result__set.html',1,'dbiplus']]],
  ['retardedasynccallbackhandler_25',['RetardedAsyncCallbackHandler',['../d8/d43/class_x_b_m_c_addon_1_1_retarded_async_callback_handler.html',1,'XBMCAddon']]],
  ['rfft_26',['RFFT',['../df/df5/class_r_f_f_t.html',1,'']]],
  ['rssset_27',['RssSet',['../d2/db3/struct_rss_set.html',1,'']]],
  ['rt_5fmetrics_28',['rt_metrics',['../df/db3/structrt__metrics.html',1,'']]],
  ['rt_5fmsghdr_29',['rt_msghdr',['../d1/df2/structrt__msghdr.html',1,'']]]
];
