var searchData=
[
  ['keyboard_0',['Keyboard',['../class_x_b_m_c_addon_1_1xbmc_1_1_keyboard.html',1,'XBMCAddon::xbmc']]],
  ['kodi_5faddon_5faudiodecoder_5finfo_5ftag_1',['KODI_ADDON_AUDIODECODER_INFO_TAG',['../struct_k_o_d_i___a_d_d_o_n___a_u_d_i_o_d_e_c_o_d_e_r___i_n_f_o___t_a_g.html',1,'']]],
  ['kodi_5fhttp_5fheader_2',['KODI_HTTP_HEADER',['../struct_k_o_d_i___h_t_t_p___h_e_a_d_e_r.html',1,'']]],
  ['kodi_5fversion_5ft_3',['kodi_version_t',['../group__cpp__kodi___defs.html#structkodi__version__t',1,'']]],
  ['koditoaddonfunctable_5faddon_4',['KodiToAddonFuncTable_Addon',['../struct_kodi_to_addon_func_table___addon.html',1,'']]],
  ['koditoaddonfunctable_5faudiodecoder_5',['KodiToAddonFuncTable_AudioDecoder',['../struct_kodi_to_addon_func_table___audio_decoder.html',1,'']]],
  ['koditoaddonfunctable_5faudioencoder_6',['KodiToAddonFuncTable_AudioEncoder',['../struct_kodi_to_addon_func_table___audio_encoder.html',1,'']]],
  ['koditoaddonfunctable_5fgame_7',['KodiToAddonFuncTable_Game',['../struct_kodi_to_addon_func_table___game.html',1,'']]],
  ['koditoaddonfunctable_5fimagedecoder_8',['KodiToAddonFuncTable_ImageDecoder',['../struct_kodi_to_addon_func_table___image_decoder.html',1,'']]],
  ['koditoaddonfunctable_5finputstream_9',['KodiToAddonFuncTable_InputStream',['../struct_kodi_to_addon_func_table___input_stream.html',1,'']]],
  ['koditoaddonfunctable_5fperipheral_10',['KodiToAddonFuncTable_Peripheral',['../struct_kodi_to_addon_func_table___peripheral.html',1,'']]],
  ['koditoaddonfunctable_5fpvr_11',['KodiToAddonFuncTable_PVR',['../struct_kodi_to_addon_func_table___p_v_r.html',1,'']]],
  ['koditoaddonfunctable_5fscreensaver_12',['KodiToAddonFuncTable_Screensaver',['../struct_kodi_to_addon_func_table___screensaver.html',1,'']]],
  ['koditoaddonfunctable_5fvfsentry_13',['KodiToAddonFuncTable_VFSEntry',['../struct_kodi_to_addon_func_table___v_f_s_entry.html',1,'']]],
  ['koditoaddonfunctable_5fvideocodec_14',['KodiToAddonFuncTable_VideoCodec',['../struct_kodi_to_addon_func_table___video_codec.html',1,'']]],
  ['koditoaddonfunctable_5fvisualization_15',['KodiToAddonFuncTable_Visualization',['../struct_kodi_to_addon_func_table___visualization.html',1,'']]]
];
