var searchData=
[
  ['c_2b_2b_0',['C++',['../d1/ddf/group__cpp.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_1',['Callback functions from Kodi to add-on',['../dd/d1b/group__cpp__kodi__gui__windows__window__callbacks.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_2',['Callback functions from Kodi to Add-On',['../dd/d41/group__python___player_c_b.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don_3',['Callback functions from Kodi to add-on',['../d4/df8/group__python__xbmcgui__window__cb.html',1,'']]],
  ['callbacks_20getdirectory_28_29_4',['Callbacks GetDirectory()',['../d8/dfe/group__cpp__kodi__addon__vfs__general__cb___get_directory.html',1,'']]],
  ['child_20functions_5',['Child Functions',['../dc/d01/group__cpp__kodi__gui__helpers__gl___c_shader_program__child.html',1,'']]],
  ['class_20audiodecoderinfotag_6',['class AudioDecoderInfoTag',['../d2/d69/group__cpp__kodi__addon__audiodecoder___defs___audio_decoder_info_tag.html',1,'']]],
  ['class_20audioengineformat_7',['class AudioEngineFormat',['../d2/de7/group__cpp__kodi__audioengine___defs___audio_engine_format.html',1,'']]],
  ['class_20cachestatus_8',['class CacheStatus',['../d6/d53/group__cpp__kodi__vfs___defs___cache_status.html',1,'']]],
  ['class_20caddonbase_9',['class CAddonBase',['../dc/d7b/group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['class_20caestream_10',['class CAEStream',['../d0/db0/group__cpp__kodi__audioengine___c_a_e_stream.html',1,'']]],
  ['class_20cdirentry_11',['class CDirEntry',['../d7/ded/group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['class_20cdllhelper_12',['class CDllHelper',['../dd/dea/group__cpp__kodi__tools___c_dll_helper.html',1,'']]],
  ['class_20cendtime_13',['class CEndTime',['../d5/dd9/group__cpp__kodi__tools___c_end_time.html',1,'']]],
  ['class_20cinterfaceandroidsystem_14',['class CInterfaceAndroidSystem',['../da/d34/group__cpp__kodi__platform___c_interface_android_system.html',1,'']]],
  ['class_20csettingvalue_15',['class CSettingValue',['../df/d58/group__cpp__kodi__addon__addonbase___defs___c_setting_value.html',1,'']]],
  ['class_20cthread_16',['class CThread',['../d4/dfd/group__cpp__kodi__tools___c_thread.html',1,'']]],
  ['class_20ctimer_17',['class CTimer',['../d2/d33/group__cpp__kodi__tools___c_timer.html',1,'']]],
  ['class_20driverprimitive_18',['class DriverPrimitive',['../d5/d57/group__cpp__kodi__addon__peripheral___defs___joystick___driver_primitive.html',1,'']]],
  ['class_20filestatus_19',['class FileStatus',['../df/d08/group__cpp__kodi__vfs___defs___file_status.html',1,'']]],
  ['class_20gamecontrollerlayout_20',['class GameControllerLayout',['../dd/d1e/group__cpp__kodi__addon__game___defs___input_types___game_controller_layout.html',1,'']]],
  ['class_20httpheader_21',['class HttpHeader',['../d9/d25/group__cpp__kodi__vfs___defs___http_header.html',1,'']]],
  ['class_20inputstreamcapabilities_22',['class InputstreamCapabilities',['../dc/d43/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_capabilities.html',1,'']]],
  ['class_20inputstreamcontentlightmetadata_23',['class InputstreamContentlightMetadata',['../d9/d31/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_contentlight_metadata.html',1,'']]],
  ['class_20inputstreaminfo_24',['class InputstreamInfo',['../db/d82/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_info.html',1,'']]],
  ['class_20inputstreammasteringmetadata_25',['class InputstreamMasteringMetadata',['../da/d1e/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_mastering_metadata.html',1,'']]],
  ['class_20inputstreamproperty_26',['class InputstreamProperty',['../d6/df1/group__cpp__kodi__addon__inputstream___defs___inputstream_property.html',1,'']]],
  ['class_20inputstreamtimes_27',['class InputstreamTimes',['../dc/d8d/group__cpp__kodi__addon__inputstream___defs___interface___inputstream_times.html',1,'']]],
  ['class_20itimercallback_28',['class ITimerCallback',['../df/de6/group__cpp__kodi__tools___c_timer___c_b.html',1,'']]],
  ['class_20joystick_29',['class Joystick',['../d0/da1/group__cpp__kodi__addon__peripheral___defs___joystick___joystick.html',1,'']]],
  ['class_20joystickfeature_30',['class JoystickFeature',['../db/d89/group__cpp__kodi__addon__peripheral___defs___joystick___joystick_feature.html',1,'']]],
  ['class_20peripheral_31',['class Peripheral',['../d3/da4/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral.html',1,'']]],
  ['class_20peripheralcapabilities_32',['class PeripheralCapabilities',['../d6/dbe/group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities.html',1,'']]],
  ['class_20peripheralevent_33',['class PeripheralEvent',['../d7/d89/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event.html',1,'']]],
  ['class_20pvrcapabilities_34',['class PVRCapabilities',['../d3/df7/group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities.html',1,'']]],
  ['class_20pvrchannel_35',['class PVRChannel',['../df/d03/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channel.html',1,'']]],
  ['class_20pvrchannelgroup_36',['class PVRChannelGroup',['../d3/dec/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group.html',1,'']]],
  ['class_20pvrchannelgroupmember_37',['class PVRChannelGroupMember',['../de/da7/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_member.html',1,'']]],
  ['class_20pvrchannelgroupmembersresultset_38',['class PVRChannelGroupMembersResultSet',['../d9/d7f/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_group_members_result_set.html',1,'']]],
  ['class_20pvrchannelgroupsresultset_39',['class PVRChannelGroupsResultSet',['../d9/d68/group__cpp__kodi__addon__pvr___defs___channel_group___p_v_r_channel_groups_result_set.html',1,'']]],
  ['class_20pvrchannelsresultset_40',['class PVRChannelsResultSet',['../dc/d71/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_channels_result_set.html',1,'']]],
  ['class_20pvrcodec_41',['class PVRCodec',['../d1/d0c/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_codec.html',1,'']]],
  ['class_20pvrdescrambleinfo_42',['class PVRDescrambleInfo',['../df/d52/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_descramble_info.html',1,'']]],
  ['class_20pvredlentry_43',['class PVREDLEntry',['../d7/d48/group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r_e_d_l_entry.html',1,'']]],
  ['class_20pvrepgtag_44',['class PVREPGTag',['../d1/dfb/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tag.html',1,'']]],
  ['class_20pvrepgtagsresultset_45',['class PVREPGTagsResultSet',['../da/d89/group__cpp__kodi__addon__pvr___defs__epg___p_v_r_e_p_g_tags_result_set.html',1,'']]],
  ['class_20pvrmenuhook_46',['class PVRMenuhook',['../d5/db8/group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r_menuhook.html',1,'']]],
  ['class_20pvrrecording_47',['class PVRRecording',['../d5/d9e/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recording.html',1,'']]],
  ['class_20pvrrecordingsresultset_48',['class PVRRecordingsResultSet',['../d0/dac/group__cpp__kodi__addon__pvr___defs___recording___p_v_r_recordings_result_set.html',1,'']]],
  ['class_20pvrsignalstatus_49',['class PVRSignalStatus',['../d8/dd4/group__cpp__kodi__addon__pvr___defs___channel___p_v_r_signal_status.html',1,'']]],
  ['class_20pvrstreamproperties_50',['class PVRStreamProperties',['../dc/d27/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties.html',1,'']]],
  ['class_20pvrstreamproperty_51',['class PVRStreamProperty',['../d8/d5c/group__cpp__kodi__addon__pvr___defs___general___inputstream___p_v_r_stream_property.html',1,'']]],
  ['class_20pvrstreamproperty_20_26_20definition_20pvr_5fstream_5fproperty_52',['class PVRStreamProperty &amp; definition PVR_STREAM_PROPERTY',['../db/de7/group__cpp__kodi__addon__pvr___defs___general___inputstream.html',1,'']]],
  ['class_20pvrstreamtimes_53',['class PVRStreamTimes',['../de/d74/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times.html',1,'']]],
  ['class_20pvrtimer_54',['class PVRTimer',['../dd/dd8/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer.html',1,'']]],
  ['class_20pvrtimersresultset_55',['class PVRTimersResultSet',['../d8/d1b/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timers_result_set.html',1,'']]],
  ['class_20pvrtimertype_56',['class PVRTimerType',['../d4/dd4/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type.html',1,'']]],
  ['class_20pvrtypeintvalue_57',['class PVRTypeIntValue',['../d8/d9f/group__cpp__kodi__addon__pvr___defs___p_v_r_type_int_value.html',1,'']]],
  ['class_20streamcryptosession_58',['class StreamCryptoSession',['../dd/dba/group__cpp__kodi__addon__inputstream___defs___stream_encryption___stream_crypto_session.html',1,'']]],
  ['class_20stringutils_59',['class StringUtils',['../df/d5a/group__cpp__kodi__tools___string_utils.html',1,'']]],
  ['class_20vfsurl_60',['class VFSUrl',['../dd/d23/group__cpp__kodi__addon__vfs___defs___v_f_s_url.html',1,'']]],
  ['class_20videocodecinitdata_61',['class VideoCodecInitdata',['../d2/dbb/group__cpp__kodi__addon__videocodec___defs___video_codec_initdata.html',1,'']]],
  ['class_20visualizationtrack_62',['class VisualizationTrack',['../d1/d1e/group__cpp__kodi__addon__visualization___defs___visualization_track.html',1,'']]],
  ['class_3a_20cstream_63',['Class: CStream',['../d2/d9b/group__cpp__kodi__addon__game___operation___c_stream.html',1,'']]],
  ['cmake_20addon_20creation_20structure_64',['CMake addon creation structure',['../d0/dbc/group__cpp__cmake.html',1,'']]],
  ['control_65',['Control',['../d9/d2a/group__python__xbmcgui__control.html',1,'']]],
  ['control_20button_66',['Control Button',['../d9/d72/group__cpp__kodi__gui__windows__controls___c_button.html',1,'']]],
  ['control_20edit_67',['Control Edit',['../d9/d7c/group__cpp__kodi__gui__windows__controls___c_edit.html',1,'']]],
  ['control_20fade_20label_68',['Control Fade Label',['../d2/d86/group__cpp__kodi__gui__windows__controls___c_fade_label.html',1,'']]],
  ['control_20image_69',['Control Image',['../d8/dea/group__cpp__kodi__gui__windows__controls___c_image.html',1,'']]],
  ['control_20label_70',['Control Label',['../d5/d2b/group__cpp__kodi__gui__windows__controls___c_label.html',1,'']]],
  ['control_20progress_71',['Control Progress',['../d0/d04/group__cpp__kodi__gui__windows__controls___c_progress.html',1,'']]],
  ['control_20radio_20button_72',['Control Radio Button',['../d2/d21/group__cpp__kodi__gui__windows__controls___c_radio_button.html',1,'']]],
  ['control_20rendering_73',['Control Rendering',['../dd/df5/group__cpp__kodi__gui__windows__controls___c_rendering.html',1,'']]],
  ['control_20settings_20slider_74',['Control Settings Slider',['../d1/dd9/group__cpp__kodi__gui__windows__controls___c_settings_slider.html',1,'']]],
  ['control_20slider_75',['Control Slider',['../d9/d7f/group__cpp__kodi__gui__windows__controls___c_slider.html',1,'']]],
  ['control_20spin_76',['Control Spin',['../de/db4/group__cpp__kodi__gui__windows__controls___c_spin.html',1,'']]],
  ['control_20text_20box_77',['Control Text Box',['../df/d0b/group__cpp__kodi__gui__windows__controls___c_text_box.html',1,'']]],
  ['controller_20input_78',['Controller Input',['../df/db3/group__cpp__kodi__addon__peripheral___docs___controller_input.html',1,'']]],
  ['controls_79',['Controls',['../dd/d87/group__controls.html',1,'']]]
];
